version: '3'
services:
  api:
    image: external-pld-app
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app

networks:
  backend:
    driver: bridge