version: '3'
services:
  api:
    image: internal-pld-app
    build: .
    networks:
      - backend
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
  mongo:
    image: mongo
    restart: always 
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - backend
    volumes:
      - mongoDB:/data/db

networks:
  backend:
    driver: bridge

volumes: 
  mongoDB:
    driver: local